[project]
name = "chat-logs-merger"
version = "0.1.0"
description = "Scripts to merge ExpasyGPT conversation logs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic",
    "sparql-llm",
    "datahugger-ng",
    "nanopub-sign"
]
